let APPROVED_CONSTANTS = {
  USER_APPROVED: 'USER_APPROVED',
  USER_NOT_APPROVED: 'USER_NOT_APPROVED',
  SERVER_ERROR: 'SERVER_ERROR',
  USER_REMOVED: 'USER_REMOVED'
}

module.exports = APPROVED_CONSTANTS
