let ASSIGNMENT_CONSTANTS = {
    NO_SUCH_ASSIGNMENT: "NO_SUCH_ASSIGNMENT",
    ASSIGNMENT_ADDED: "ASSIGNMENT_ADDED",
    ASSIGNMENT_NOT_ADDED: "ASSIGNMENT_NOT_ADDED"
};

module.exports = ASSIGNMENT_CONSTANTS;
