let AUTH_CONSTANTS = {
    EMAIL_ALREADY_IN_DB: "EMAIL_ALREADY_IN_DB",
    WRONG_EMAIL: "WRONG_EMAIL",
    CANT_INSERT_USER_IN_COLLECTION: "CANT_INSERT_USER_IN_COLLECTION",
    WRONG_PASSWORD: "WRONG_PASSWORD",
    USER_IS_NOT_REGISTERED: "USER_IS_NOT_REGISTERED",
    USER_IS_NOT_APPROVED: "USER_IS_NOT_APPROVED",
    USER_ADDED_IN_DB: "USER_ADDED_IN_DB",
    CORRECT_PASSWORD: "CORRECT_PASSWORD",
    NOT_LOGGED_IN: "NOT_LOGGED_IN"
};

module.exports = AUTH_CONSTANTS;
