// Errors
export const EMAIL_ALREADY_IN_DB = "EMAIL_ALREADY_IN_DB";
export const WRONG_EMAIL = "WRONG_EMAIL";
export const CANT_INSERT_USER_IN_COLLECTION = "CANT_INSERT_USER_IN_COLLECTION";
export const WRONG_PASSWORD = "WRONG_PASSWORD";
export const USER_IS_NOT_REGISTERED = "USER_IS_NOT_REGISTERED";
export const USER_IS_NOT_APPROVED = "USER_IS_NOT_APPROVED";

// Success
export const USER_ADDED_IN_DB = "USER_ADDED_IN_DB";
export const CORRECT_PASSWORD = "CORRECT_PASSWORD";
export const NOT_LOGGED_IN = "NOT_LOGGED_IN";
