let CODE_TESTING_CONSTANTS = {
  TESTS_PASSED: "TESTS_PASSED",
  TESTS_FAILED: {
    error: "TESTS_FAILED",
    on_test: -1
  },
  SERVER_ERROR: "SERVER_ERROR",
  NO_FILES_UPLOADED: "NO_FILES_UPLOADED"
};

module.exports = CODE_TESTING_CONSTANTS;
