let CODE_TESTING_CONSTANTS = {
  TESTS_PASSED: 'TESTS_PASSED',
  TESTS_FAILED: {
    error: 'TESTS_FAILED',
    on_test: -1
  },
  SERVER_ERROR: 'SERVER_ERROR',
  NO_FILES_UPLOADED: 'NO_FILES_UPLOADED',
  TESTS_ALREADY_PASSED: 'TESTS_ALREADY_PASSED'
}

module.exports = CODE_TESTING_CONSTANTS
