let CODE_TESTING_CONSTANTS = {
  TESTS_PASSED: "TESTS_PASSED",
  TESTS_FAILED: "TESTS_FAILED",
  SERVER_ERROR: "SERVER_ERROR",
  NO_FILES_UPLOADED: "NO_FILES_UPLOADED"
};

module.exports = CODE_TESTING_CONSTANTS;
